targets:
  $default:
    builders:
      source_gen:combining_builder:
        enabled: true
        options:
          build_extensions:
            '^lib/models/{{}}.dart': 'lib/data/adapter/{{}}.g.dart'