/// Flutter icons FontsCustom
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FontsCustom
///      fonts:
///       - asset: fonts/FontsCustom.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
///
import 'package:flutter/widgets.dart';

class FontsCustom {
  FontsCustom._();

  static const _kFontFam = 'FontsCustom';
  static const String? _kFontPkg = null;

  static const IconData emo_grin =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
